#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Home\Index.cshtml"
    using FeiXian.Entity;
    
    #line default
    #line hidden
    using NewLife;
    using NewLife.Cube;
    using NewLife.Reflection;
    using NewLife.Web;
    using XCode;
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<Dictionary<String, IList<Record>>>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    var last = ViewBag.Last as IList<Record>;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div>\r\n    <h1>代码之巅，天外飞仙！</h1>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Home\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Home\Index.cshtml"
     foreach (var item in Model)
    {

            
            #line default
            #line hidden
WriteLiteral("        <h3>");

            
            #line 12 "..\..\Views\Home\Index.cshtml"
       Write(item.Key);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table border-area\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Views\Home\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Home\Index.cshtml"
                 foreach (var rc in item.Value)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   <div><h3><a");

WriteAttribute("href", Tuple.Create(" href=\"", 490), Tuple.Create("\"", 499)
, Tuple.Create(Tuple.Create("", 497), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 497), false)
);

WriteLiteral(" title=\"每秒处理速度\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\Home\Index.cshtml"
                                                            Write(rc.Score.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</a><sub>TPS</sub> &nbsp; ");

            
            #line 19 "..\..\Views\Home\Index.cshtml"
                                                                                                              Write(rc.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3></div>\r\n                            <div>");

            
            #line 20 "..\..\Views\Home\Index.cshtml"
                            Write(rc.Processor);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div");

WriteLiteral(" class=\"text-big\"");

WriteLiteral("> ");

            
            #line 21 "..\..\Views\Home\Index.cshtml"
                                              Write(rc.Config);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            <div");

WriteLiteral(" style=\"margin-top: 10px;\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" title=\"主频\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-heart\"");

WriteLiteral(" style=\"color: deeppink;\"");

WriteLiteral("></i> ");

            
            #line 24 "..\..\Views\Home\Index.cshtml"
                                                                                                                   Write(rc.Frequency.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" MHz</span>\r\n                                    <span");

WriteLiteral(" title=\"内部\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-star\"");

WriteLiteral(" style=\"color: mediumpurple;\"");

WriteLiteral("></i> ");

            
            #line 25 "..\..\Views\Home\Index.cshtml"
                                                                                                                      Write(rc.Memory.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" MB</span>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"col-md-6 text-right\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Home\Index.cshtml"
                                                            Write(rc.CreateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </div>\r\n                        </td>\r\n      " +
"              </tr>\r\n");

            
            #line 31 "..\..\Views\Home\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </table>\r\n        </div>\r\n");

            
            #line 34 "..\..\Views\Home\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"table border-area\"");

WriteLiteral(">\r\n            <thead>最新提交</thead>\r\n");

            
            #line 39 "..\..\Views\Home\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Home\Index.cshtml"
             foreach (var rc in last)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>\r\n                        <div><h3>" +
"<a");

WriteAttribute("href", Tuple.Create(" href=\"", 1691), Tuple.Create("\"", 1700)
, Tuple.Create(Tuple.Create("", 1698), Tuple.Create<System.Object, System.Int32>(Href("~/")
, 1698), false)
);

WriteLiteral(" title=\"每秒处理速度\"");

WriteLiteral(">");

            
            #line 43 "..\..\Views\Home\Index.cshtml"
                                                        Write(rc.Score.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral("</a><sub>TPS</sub> &nbsp; ");

            
            #line 43 "..\..\Views\Home\Index.cshtml"
                                                                                                          Write(rc.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3></div>\r\n                        <div>");

            
            #line 44 "..\..\Views\Home\Index.cshtml"
                        Write(rc.Processor);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        <div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" title=\"主频\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-heart\"");

WriteLiteral(" style=\"color: deeppink;\"");

WriteLiteral("></i> ");

            
            #line 47 "..\..\Views\Home\Index.cshtml"
                                                                                                               Write(rc.Frequency.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" MHz</span>\r\n                                <span");

WriteLiteral(" title=\"内部\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-star\"");

WriteLiteral(" style=\"color: mediumpurple;\"");

WriteLiteral("></i> ");

            
            #line 48 "..\..\Views\Home\Index.cshtml"
                                                                                                                  Write(rc.Memory.ToString("n0"));

            
            #line default
            #line hidden
WriteLiteral(" MB</span>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-md-6 text-right\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\Home\Index.cshtml"
                                                        Write(rc.CreateTime.ToFullString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </div>\r\n                    </td>\r\n              " +
"  </tr>\r\n");

            
            #line 54 "..\..\Views\Home\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
